using Amazon.Lambda.Core;
using Amazon.Lambda.Serialization.SystemTextJson;

// Assembly attribute to activate the JSON serializer generated by AWS Lambda tools
[assembly: LambdaSerializer(typeof(DefaultLambdaJsonSerializer))]

namespace User.API;

public class PostSignupConfirmationHandler 
{
    public async Task<Amazon.Lambda.CognitoEvents.CognitoPostConfirmationResponse> PostSignupConfirmationFunctionHandler(
            Amazon.Lambda.CognitoEvents.CognitoPostConfirmationEvent cognitoEvent, ILambdaContext context)
    {
        context.Logger.LogLine("Post Confirmation triggered for user: " + cognitoEvent.UserName);
        context.Logger.LogLine("Trigger source: " + cognitoEvent.TriggerSource);

        // Example of accessing user attributes
        if (cognitoEvent.Request.UserAttributes.ContainsKey("email"))
        {
            string userEmail = cognitoEvent.Request.UserAttributes["email"];
            context.Logger.LogLine("User email: " + userEmail);

            // You can add logic here to perform actions, e.g.,
            // * Add user to a DynamoDB table
            // * Send a welcome email using Amazon SES
        }

        // Important: The function must return the event object
        // to indicate successful completion back to Amazon Cognito.
        return new Amazon.Lambda.CognitoEvents.CognitoPostConfirmationResponse();
    }
}
